// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
// Load secrets from .env.local (gitignored). Falls back to .env if present.
config({ path: ".env.local" });
config();
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Runtime connection. DATABASE_URL points at the transaction-mode pooler.
    // For `prisma migrate`/`db push`, run against the session-mode pooler, e.g.:
    //   DATABASE_URL="$DIRECT_URL" npx prisma migrate dev
    // (Prisma 7 no longer supports a separate `directUrl` here.)
    url: process.env["DATABASE_URL"],
  },
});
