// DOSSIER — an entity page + its 1-hop neighborhood rendered to shareable,
// CITED markdown: "everything we know about Acme, and where each claim came
// from". A projection like every other view — derived from the same
// KnowledgeEntityView the dashboard loads, nothing stored. Pure module (type
// imports only) so it unit-tests under node:test; the download route feeds it.

import type { FactSourceView, KnowledgeEntityView, KnowledgeFactView } from "./types";

const pretty = (predicate: string) => predicate.replace(/_/g, " ");
const title = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

/** Filesystem-safe download name for a dossier ("Acme Inc" → "acme-inc"). */
export function dossierFilename(label: string): string {
  const slug = label
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
  return `${slug || "entity"}-dossier.md`;
}

/** One numbered evidence source; identical messages collapse to one number. */
interface SourceEntry {
  n: number;
  s: FactSourceView;
}

function sourceKey(s: FactSourceView): string {
  return [s.channel, s.sender ?? "", s.subject ?? "", s.receivedAt ?? ""].join("|");
}

function sourceLine(e: SourceEntry): string {
  const bits = [e.s.channel, e.s.sender, e.s.subject ? `“${e.s.subject}”` : null, e.s.receivedAt?.slice(0, 10)]
    .filter(Boolean)
    .join(" · ");
  const quote = e.s.snippet ? ` — "${e.s.snippet}"` : "";
  return `[${e.n}]: ${bits}${quote}`;
}

/**
 * Render the dossier. Deterministic: `generatedOn` is injected (YYYY-MM-DD).
 * Returns null when the entity isn't in the view (caller 404s).
 */
export function buildDossier(
  entities: KnowledgeEntityView[],
  entityId: string,
  generatedOn: string,
): string | null {
  const target = entities.find((e) => e.id === entityId);
  if (!target) return null;
  const byId = new Map(entities.map((e) => [e.id, e]));

  // Citation numbering: first appearance wins, duplicates collapse.
  const sources: SourceEntry[] = [];
  const numByKey = new Map<string, number>();
  const cite = (facts: KnowledgeFactView[]): string => {
    const ns = new Set<number>();
    for (const f of facts) {
      for (const s of f.provenance) {
        const key = sourceKey(s);
        let n = numByKey.get(key);
        if (!n) {
          n = sources.length + 1;
          numByKey.set(key, n);
          sources.push({ n, s });
        }
        ns.add(n);
      }
    }
    return [...ns].sort((a, b) => a - b).map((n) => `[${n}]`).join("");
  };

  const factLines = (e: KnowledgeEntityView): string[] =>
    e.facts.map((f) => {
      const value = f.ref ? `→ ${f.value}` : f.value;
      const c = cite([f]);
      return `- **${pretty(f.predicate)}**: ${value}${c ? ` ${c}` : ""}`;
    });

  // 1-hop neighborhood: whatever the entity points at + whatever points at it.
  const outgoing = target.facts.filter((f) => f.ref && f.refId && byId.has(f.refId));
  const incoming: { from: KnowledgeEntityView; predicate: string; facts: KnowledgeFactView[] }[] = [];
  for (const e of entities) {
    if (e.id === target.id) continue;
    const pointing = e.facts.filter((f) => f.ref && f.refId === target.id);
    if (pointing.length) incoming.push({ from: e, predicate: pointing[0].predicate, facts: pointing });
  }
  const neighborIds = [
    ...new Set([...outgoing.map((f) => f.refId!), ...incoming.map((i) => i.from.id)]),
  ].filter((id) => id !== target.id);

  const md: string[] = [];
  md.push(`# ${target.label}`);
  md.push("");
  md.push(`_${title(target.kind)} · dossier generated by datamodo on ${generatedOn} — every claim cites its source._`);
  const keys = Object.entries(target.naturalKeys ?? {});
  if (keys.length) {
    md.push("");
    md.push(keys.map(([k, v]) => `\`${pretty(k)}: ${v}\``).join(" · "));
  }

  if (target.bodyMd) {
    md.push("");
    md.push("## Summary");
    md.push("");
    md.push(target.bodyMd.trim());
  }

  const attrs = target.facts.filter((f) => !f.ref);
  if (attrs.length) {
    md.push("");
    md.push("## What we know");
    md.push("");
    for (const f of attrs) {
      const c = cite([f]);
      md.push(`- **${pretty(f.predicate)}**: ${f.value}${c ? ` ${c}` : ""}`);
    }
  }

  if (outgoing.length || incoming.length) {
    md.push("");
    md.push("## Connections");
    md.push("");
    for (const f of outgoing) {
      const c = cite([f]);
      const kind = byId.get(f.refId!)?.kind;
      md.push(`- **${pretty(f.predicate)}** → ${f.value}${kind ? ` _(${kind})_` : ""}${c ? ` ${c}` : ""}`);
    }
    for (const i of incoming) {
      const c = cite(i.facts);
      md.push(`- ${i.from.label} _(${i.from.kind})_ — **${pretty(i.predicate)}** → ${target.label}${c ? ` ${c}` : ""}`);
    }
  }

  if (neighborIds.length) {
    md.push("");
    md.push("## Around it");
    for (const id of neighborIds) {
      const e = byId.get(id);
      if (!e) continue;
      md.push("");
      md.push(`### ${e.label} _(${e.kind})_`);
      const lines = factLines(e);
      if (lines.length) md.push(...lines);
      else md.push("- _nothing captured yet_");
    }
  }

  md.push("");
  md.push("## Sources");
  md.push("");
  if (sources.length) {
    for (const e of sources) md.push(sourceLine(e));
  } else {
    md.push("_No message-level provenance recorded for the facts above._");
  }
  md.push("");
  return md.join("\n");
}
