// Unit tests for the pure dossier renderer (lib/datamodo/dossier.ts).
// Run with: npm test

import { test } from "node:test";
import assert from "node:assert/strict";
import { buildDossier, dossierFilename } from "../lib/datamodo/dossier.ts";
import type { FactSourceView, KnowledgeEntityView, KnowledgeFactView } from "../lib/datamodo/types.ts";

const src = (over: Partial<FactSourceView> = {}): FactSourceView => ({
  channel: "email",
  sender: "billing@acme.com",
  subject: "Invoice attached",
  preview: null,
  snippet: "total due: 1200 EUR",
  receivedAt: "2026-07-02T09:00:00.000Z",
  ...over,
});

const fact = (predicate: string, value: string, over: Partial<KnowledgeFactView> = {}): KnowledgeFactView => ({
  predicate, value, ref: false, refId: null, sources: 0, provenance: [], ...over,
});

const ent = (id: string, kind: string, label: string, facts: KnowledgeFactView[] = [], over: Partial<KnowledgeEntityView> = {}): KnowledgeEntityView => ({
  id, kind, label, naturalKeys: {}, facts, edges: 0, bodyMd: null, graphPin: null, ...over,
});

const WORLD = [
  ent("acme", "company", "Acme Inc", [fact("industry", "renewables", { provenance: [src({ subject: "Intro", snippet: null })] })], { naturalKeys: { email: "hello@acme.com" } }),
  ent("inv", "invoice", "INV-9", [
    fact("amount", "1200 EUR", { provenance: [src()] }),
    fact("issued_by", "Acme Inc", { ref: true, refId: "acme", provenance: [src()] }),
  ]),
  ent("doc", "document", "msa.pdf", [fact("mentions", "Acme Inc", { ref: true, refId: "acme" })], { bodyMd: "# MSA\nKey terms." }),
];

test("buildDossier: header, keys, facts with citations, sources footer", () => {
  const md = buildDossier(WORLD, "acme", "2026-07-10")!;
  assert.match(md, /^# Acme Inc/);
  assert.match(md, /dossier generated by datamodo on 2026-07-10/);
  assert.match(md, /`email: hello@acme\.com`/);
  // The attribute cites [1]; the sources footer resolves it.
  assert.match(md, /- \*\*industry\*\*: renewables \[1\]/);
  assert.match(md, /\[1\]: email · billing@acme\.com · “Intro” · 2026-07-02/);
});

test("buildDossier: connections cover both directions; neighborhood renders 1 hop", () => {
  const md = buildDossier(WORLD, "acme", "2026-07-10")!;
  // Incoming: the invoice and the document point at Acme.
  assert.match(md, /- INV-9 _\(invoice\)_ — \*\*issued by\*\* → Acme Inc \[\d\]/);
  assert.match(md, /- msa\.pdf _\(document\)_ — \*\*mentions\*\* → Acme Inc/);
  // Around it: each neighbor gets its facts.
  assert.match(md, /### INV-9 _\(invoice\)_/);
  assert.match(md, /- \*\*amount\*\*: 1200 EUR \[\d\]/);
  assert.match(md, /### msa\.pdf _\(document\)_/);
});

test("buildDossier: identical messages collapse to one citation number", () => {
  const md = buildDossier(WORLD, "inv", "2026-07-10")!;
  // amount and issued_by share the same source message → the same [n].
  const amount = /- \*\*amount\*\*: 1200 EUR \[(\d)\]/.exec(md);
  const issued = /- \*\*issued by\*\* → Acme Inc _\(company\)_ \[(\d)\]/.exec(md);
  assert.ok(amount && issued, "both lines cite");
  assert.equal(amount![1], issued![1]);
  // The footer lists that exact message once (the "Intro" email is a
  // different source and rightly gets its own number).
  assert.equal(md.match(/\[\d\]: email · billing@acme\.com · “Invoice attached”/g)!.length, 1);
});

test("buildDossier: thick nodes embed their summary body", () => {
  const md = buildDossier(WORLD, "doc", "2026-07-10")!;
  assert.match(md, /## Summary\n\n# MSA\nKey terms\./);
});

test("buildDossier: unknown entity → null; no provenance → honest footer", () => {
  assert.equal(buildDossier(WORLD, "nope", "2026-07-10"), null);
  const bare = [ent("x", "thing", "Widget", [fact("color", "red")])];
  const md = buildDossier(bare, "x", "2026-07-10")!;
  assert.match(md, /- \*\*color\*\*: red\n/);
  assert.match(md, /_No message-level provenance recorded/);
});

test("dossierFilename: slugs safely", () => {
  assert.equal(dossierFilename("Acme Inc"), "acme-inc-dossier.md");
  assert.equal(dossierFilename("Ünïcode / GmbH & Co."), "unicode-gmbh-co-dossier.md");
  assert.equal(dossierFilename("!!!"), "entity-dossier.md");
});
