#!/usr/bin/env bash
# Session-start setup for the datamodo repo.
#
# Configure this as the environment's session-start / setup command:
#   bash scripts/session-setup.sh
#
# It reads the secrets injected as environment variables (set in the cloud
# environment settings) and materializes .env.local so Next.js and Prisma pick
# them up. .env.local is gitignored — nothing secret is committed.
set -euo pipefail
cd "$(dirname "$0")/.."

REF="${SUPABASE_PROJECT_REF:-dywkfirozofxyohqmxrn}"
REGION="${SUPABASE_REGION:-aws-0-eu-west-1}"
SITE_URL="${NEXT_PUBLIC_SITE_URL:-http://localhost:3000}"

# Derive Postgres connection strings from the DB password when not provided.
if [ -z "${DATABASE_URL:-}" ] && [ -n "${SUPABASE_DB_PASSWORD:-}" ]; then
  DATABASE_URL="postgresql://postgres.${REF}:${SUPABASE_DB_PASSWORD}@${REGION}.pooler.supabase.com:6543/postgres?pgbouncer=true"
fi
if [ -z "${DIRECT_URL:-}" ] && [ -n "${SUPABASE_DB_PASSWORD:-}" ]; then
  DIRECT_URL="postgresql://postgres.${REF}:${SUPABASE_DB_PASSWORD}@${REGION}.pooler.supabase.com:5432/postgres"
fi

SUPA_URL="${NEXT_PUBLIC_SUPABASE_URL:-}"

{
  echo "# Generated by scripts/session-setup.sh — do not edit by hand."
  echo "NEXT_PUBLIC_SITE_URL=${SITE_URL}"
  echo "NEXT_PUBLIC_SUPABASE_URL=${SUPA_URL}"
  echo "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:-}"
  echo "SUPABASE_URL=${SUPABASE_URL:-$SUPA_URL}"
  echo "SUPABASE_PUBLISHABLE_KEY=${SUPABASE_PUBLISHABLE_KEY:-${NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:-}}"
  echo "SUPABASE_SECRET_KEY=${SUPABASE_SECRET_KEY:-}"
  echo "SUPABASE_JWKS_URL=${SUPABASE_JWKS_URL:-${SUPA_URL}/auth/v1/.well-known/jwks.json}"
  echo "INGEST_WEBHOOK_SECRET=${INGEST_WEBHOOK_SECRET:-}"
  echo "DATABASE_URL=\"${DATABASE_URL:-}\""
  echo "DIRECT_URL=\"${DIRECT_URL:-}\""
} > .env.local

echo "Wrote .env.local (keys: $(grep -oE '^[A-Z_]+' .env.local | tr '\n' ' '))"

# Install deps and generate the Prisma client.
if [ -f package-lock.json ]; then
  npm ci
else
  npm install
fi
npx prisma generate

echo "session-setup: done."
